### ISSUE TITLE
can i  use cpu to train only?

### ISSUE THREAD

**Issue by pzy5678** [Chen-Wang-CUHK/ExHiRD-DKG#10]
i don't have a gpu. 
When i change the "gpu_ranks" to -1, it  doesn't seem to work. 
So  i change the device's value to "cpu",  finally i get a TypeError :" type torch.cuda.LongTensor not available.".
How can i deal with it?
Thanks.

**Comment by Chen-Wang-CUHK** [comment]
> i don't have a gpu.
> When i change the "gpu_ranks" to -1, it doesn't seem to work.
> So i change the device's value to "cpu", finally i get a TypeError :" type torch.cuda.LongTensor not available.".
> How can i deal with it?
> Thanks.

I think modifications are required to run the code on CPU. For these explicitly-defined "torch.cuda" tensors, we need to change them to "torch" tensors which can be defined on CPU. But I do not recommend you to run the code on CPU because of slow speed.

**Comment by pzy5678** [comment]
Thanks.
